name:                remez
version:             0.1.0.0
github:              "hdehacks/remez"
license:             GPLv3
author:              "Joshua Maravelias"
maintainer:          "maravelias@protonmail.com"
copyright:           "2021 Joshua Maravelias"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/hdehacks/remez#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- assoc-list == 0.1.0.1

library:
  source-dirs: src

executables:
  my-game-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - remez

tests:
  my-game-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - remez
